### ISSUE TITLE
WSL Ubuntu Fail to read log

### ISSUE THREAD

**Issue by Handri-Kosada** [ericaltendorf/plotman#108]
I try to run plotman in WSL 1 Ubuntu 20 LTS.
the plot drive is in /mnt/g ( windows G drive)

it can run, but there is error as following :

it creates log file with weird char because windows doesnt support  file naming with char : ?  
2021-04-12-150855.log

Found plotting process PID 38, but could not find logfile in its open files:

**Comment by altendky** [comment]
What is the full traceback?

Though mostly I expect this is about just not using `:` in file names.  Looks like it is as simple as changing how we write the file name since we seem not to care when detecting the log file.

https://github.com/ericaltendorf/plotman/blob/45fbb1e6e0796bedb57d42cf61c75bd5b6587ef5/src/plotman/job.py#L142-L150

https://github.com/ericaltendorf/plotman/blob/45fbb1e6e0796bedb57d42cf61c75bd5b6587ef5/src/plotman/manager.py#L112-L113

It seems like [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) just offers `:` or nothing as time separator.  [RFC3339](https://tools.ietf.org/html/rfc3339) maybe only references `:`.  It would be nice to follow a standard but we may end up deviating.

I would rather not make this OS dependant.

**Comment by Handri-Kosada** [comment]
$ plotman status
Found plotting process PID 7469, but could not find logfile in its open files:
Found plotting process PID 8106, but could not find logfile in its open files:
Found plotting process PID 8672, but could not find logfile in its open files:
 plot id    k            tmp             dst   wall   phase   tmp    pid   stat    mem   user    sys   io
--------   32   /mnt/g/temp/   /mnt/g/plots/   2:44     ?:?     0   8672    RUN   7.4G   4:54   0:14   0s
--------   32   /mnt/g/temp/   /mnt/g/plots/   3:28     ?:?     0   8106    RUN   7.4G   5:26   0:18   0s
--------   32   /mnt/g/temp/   /mnt/g/plots/   3:42     ?:?     0   7469    RUN   7.4G   5:36   0:20   0s

**Comment by Handri-Kosada** [comment]
Change this :

 logfile = os.path.join(dir_cfg['log'], 
         datetime.now().strftime('%Y-%m-%d-%H-%M-%S.log')) 

Still the same error 

~/chia-beta$ plotman status

Found plotting process PID 10912, but could not find logfile in its open files:
 plot id    k            tmp             dst   wall   phase   tmp     pid   stat      mem   user   sys   io
--------   32   /mnt/g/temp/   /mnt/g/plots/    17s     ?:?     0   10912    SLP   826.2M    12s    7s   0s

**Comment by Handri-Kosada** [comment]
@altendky 
Please let me know what code & where to add in the file to debug and print / trace the error. 
I'm not very good with python. Will post the result here.

**Comment by altendky** [comment]
This issue still remains, but fyi, they did manage to get `--mount` working in WSL2.  @Handri-Kosada perhaps you could link the details here in case others have this trouble or otherwise want the...  workaround for this that may be a solution for other things.

**Comment by Handri-Kosada** [comment]
The full tutorial is here : 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk

Make sure to sign up insider windows dev version to proceed.

**Comment by altendky** [comment]
I personally consider the issue still open even though another scenario was found where the issue did not occur.  But, perhaps it isn't worth working on at this point.  Still, for Windows support in general we need to not use `:` afaik.
