### ISSUE TITLE
No new Plots generated

### ISSUE THREAD

**Issue by JonesiKC** [ericaltendorf/plotman#171]
Hi,

nice tool by the way and thanks! I'm new to github, so I hope it is the right way to do this.
Tonight plotman crashed somehow and didn't start a new plot.
Does plotman have a own pid somhow?
When I lookup processes on plotman or even python I can't find a pid
I did a little workaround for now

```
#!/bin/bash
#cronjob every 5 min
. /home/jre/chia-blockchain/activate
for pcount in $(ps -aux |grep "chia plots create" |grep -v grep |awk '{print $2}'| wc -l)
do
        echo "Number of Plots: $pcount"
        if [ $pcount -lt 1 ]
        then
                echo "No plot running! Starting new Plot"
                plotman plot &
                /usr/local/bin/send_telegram 
        else
                echo "All fine"
                exit 0
        fi
done
```

Thanks

**Comment by altendky** [comment]
plotman is a process so yes, it does have a process ID.  If you have just launched it in the background then you can [get the PID via `$!`](https://unix.stackexchange.com/a/30371/7644).

This question does relate to my general opinion that plotman is, at its heart, two things: a service and a monitor.  You may be interested in using the service manager on your system instead of cron.  That would manage the plotman process itself and would presumably include notification features.  I think we still need to setup the ability to explicitly run the plotman monitor without starting plots.

Side note, it looks like in the present version that the for loop and the `awk` are not needed.  Since the output is going to `wc` at the end, the `awk` wouldn't change anything.  Since `wc -l` outputs a single number, the for loop would just loop once.

**Comment by JonesiKC** [comment]
true, ``awk`` is not needed and yes the loop makes no sense :)  - it was too early in the morning to write a script.
I'm working on a systemd solution this evening I think - have to setup a spare machine first

**Comment by BasilHorowt** [comment]
Sounds like this can be closed? Because there is talk of a service, you may want to subscribe to https://github.com/ericaltendorf/plotman/issues/285 @JonesiKC
