### ISSUE TITLE
Trying to install in WIndows but getting an error

### ISSUE THREAD

**Issue by zeroarst** [ericaltendorf/plotman#188]
I am getting error with this command.
`pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main`

![2021-04-29 16_49_35-Command Prompt](https://user-images.githubusercontent.com/1834837/116512205-00516200-a90b-11eb-8460-6a24ef49e0ad.png)
```
$ pip --version
pip 21.1 from c:\users\roy\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
```
Dose it currently support Windows?

**Comment by altendky** [comment]
That particular issue has been fixed on development.  You can get it by specifying `@development` instead of `@main`.  But, no, plotman doesn't work natively on Windows at present.  Many people are running it in WSL.  See the comments in https://github.com/ericaltendorf/plotman/issues/108#issuecomment-822151350.

**Comment by BasilHorowt** [comment]
@zeroarst I'm going to close this, did you have any luck with running the development branch?
