### ISSUE TITLE
Scheduling one PARTICULAR temp drive?

### ISSUE THREAD

**Issue by MichaGithubel** [ericaltendorf/plotman#197]
In the plotman.yaml it is written:

        #Run a job on a particular temp dir only if the number of existing jobs
        # before tmpdir_stagger_phase_major tmpdir_stagger_phase_minor
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major, phase minor]

So how does one do this for one PARTICULAR temp dir like it is written above? Because with these settings it's for each of 
 all temp dirs:

        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

 I want one special rule for one SSD (/mnt/ssd1).

This is not working:

        /mnt/ssd1_stagger_phase_major: 2
         /mnt/ssd1__stagger_phase_minor: 1
        # Optional: default is 1
         /mnt/ssd1__stagger_phase_limit: 1

Thank you!

**Comment by altendky** [comment]
That isn't presently available.  We have some interest in reworking the configuration and scheduling to be more flexible, but that likely won't happen 'soon'.  Sorry.

I will note that my impression is that phase 1 staggering is primarily about CPU and memory usage due to the multi-threading etc in stage 1.  This wouldn't relate much to a specific tmp drive.  I haven't done a lot of research on this, but here's the latest graph I've seen on resource usage throughout the plotting process.

https://i.redd.it/w0jl1k9ml8t61.png
<details> <summary>expand for image</summary>

![image](https://user-images.githubusercontent.com/543719/116764693-e178cb80-a9ef-11eb-9b6d-f7a8919dacf4.png)

</details>
