### ISSUE TITLE
Logs disappear from interactive view

### ISSUE THREAD

**Issue by locque** [ericaltendorf/plotman#205]
When I'm in the interactive view while a new job is being started, the log for it will show up as expected. When I exit and come back later all of them will be gone though. Is this a known issue or is something wrong with my configuration? The logs definitely exist and are in the configured directory, they're just not being displayed.

**Comment by ericaltendorf** [comment]
The plotting logs are persisted in your logs directory.  The *plotman* logs
(record of jobs started) are not currently persisted.

**Comment by BasilHorowt** [comment]
@locque any more details on what you were thinking of here? As Eric mentioned, it seems like the intention is that the items listed in the lower area of `interactive` are more just an ephemeral view of launched processes rather than a comprehensive history.  If your jobs are starting successfully you will see them running in the top area even after restarting interactive.  I'm going to close this but if I've missed something about the issue please let me know :)
