### ISSUE TITLE
How to use Plotman Analyzer

### ISSUE THREAD

**Issue by VercauterenK** [ericaltendorf/plotman#221]
Hi All,

Can someone explain me how to user the analyzer.
I would like to analyze all finished jobs but can't find the command.

Thanks

**Comment by terryxsq** [comment]
plotman analyze ~/chialogs/*

**Comment by VercauterenK** [comment]
thanks didn't know that you needed to add the path to the logs.
Is there any way to show the values in minutes?

**Comment by ericaltendorf** [comment]
it expects the path because often you'll only want to analyze a subset of
the logs, so e.g. ~/chialogs/2021-03-* to do march.  It does not have an
option for showing times in minutes.  for some reason, it became standard
in the chia community to measure plot times in seconds or kiloseconds.  It
would be reasonable to file a feature request issue to show times in
Minutes, or Hours:Minutes, though.

**Comment by VercauterenK** [comment]
Wow didn’t know to use the day thanks for the help.

Verstuurd vanaf mijn iPhone

**Comment by VercauterenK** [comment]
Thanks all
