### ISSUE TITLE
How do you set up plotman if you don’t have any buffer drives or remotes?

### ISSUE THREAD

**Issue by locque** [ericaltendorf/plotman#231]
```
Plotman 10:09:47 (refresh 8s/20)  |  <P>lotting: (active) max jobs (12) <A>rchival: (not configured)
Jobs (12): [1        2        3      .4!]
Prefixes:  tmp=/mnt/tmp/00  dst=/mnt/dst (remote)
  #    plot id    k   tmp   dst    wall   phase    tmp      pid   stat      mem   user    sys     io
  0   5034ef88   32     .    01    5:11     3:6   168G   183727    RUN     5.2G   5:51   0:16   0:04
  1   7617d6e2   32     .    00    5:42     4:0   109G   181386    SLP   258.5M   6:13   0:18   0:04
  2   fd8db84e   32     .    01    6:14     4:0   109G   178896    SLP   324.6M   6:24   0:18   0:04
...
  9   0de15687   32     .    00   10:33     4:0   109G   158974    SLP   258.5M   7:26   0:22   0:05
 10   08496e6d   32     .    00   11:03     4:0   109G   156649    SLP   258.5M   7:22   0:23   0:06
 11   3345c620   32     .    00   11:33     4:0   109G   153899    SLP   258.5M   7:30   0:22   0:06
tmp   ready                       phases                         tmp   ready                       phases                            dst   plots   GBfree         inbnd phases
  .      --   3:6 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0      .      --   3:6 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0 4:0       00    110     0        4:0 4:0 [+2] 4:0 4:0 4:0
                                                                                                                                     01    0       11997    3:6 4:0 4:0 4:0 4:0
Archive dirs free space
<archiving not configured>
Log: 0 (<up>/<down>/<end> to scroll)
```

I mounted a second drive some time before the last job that would fit on the first one started, and expected plotman to schedule  all new jobs to that drive as soon as there was no more space on the first one. Apparently that's not the case though, and it just keeps randomly assigning jobs to one or the other, completely clogging up the queue. Is there anything I can do to divert job 11 and all the the other ones assigned to `dst/00` to `dst/01`?

Am I completely misunderstanding how plotman works? I’ve read the instructions like 10 times now, but those only explain the setup for archiving/rsyncing to a remote as a final destination and using local hard drives as temporary buffer. I don’t have any buffer drives, I only have a bunch of external hard drives that are meant to be the final destination.

Would hugely appreciate if somebody could explain how to set up plotman for local use.

**Comment by ericaltendorf** [comment]
Sorry, the instructions explain the buffering approach because that was the use case it was optimized for, and we haven't optimized the use case of filling your dst drives directly and sequentially.  You are correct, plotman does distribute plots to the dst drives randomly, and this is exacerbated for you by the fact that plotman also assumes you're archiving off the dst drives and doesn't stop plotting when they appear full.

This is a valid complaint, but since it's already covered by at least one existing issue, I'm going to suggest converting this into a discussion to try to get workaround from other users.

One option would be to only add one `dst` dir to your plotman config at a time.  When it is close to full, change it to point at your next empty drive and restart plotman; it will start sending plots there.
