### ISSUE TITLE
Plotman plots into all destination drives regardless of free space available in a drive

### ISSUE THREAD

**Issue by jayhohoho2019** [ericaltendorf/plotman#671]
**Describe the bug**
I have a script to fill 2 external HDs at a time.  When both were around 90% full I stopped the process, connected another 5 HDs (all empty), and switched to plotman (v 0.3.1).  I listed all 7 HDs as dst in the config file.  After a while both of the first two HDs had 0% free space left while the other 5 had had free space down in similar amounts which is expected.  In each of the 2 HDs that are 100% I found a partially constructed plot which had to be deleted I suppose.  Then I used plotman to kill the remaining plotting processes still with those two HDs as destination drives (there were a total of 4 that were killed like this).  

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Set up config with all 7 HDs as dst drives.  2 were 90% full, 5 were 1% full.
2. Run other programs '....'
3. Run Plotman with plot

**Expected behavior**
Plotman is expected to load balance between the dst drives, but why would it continue writing to a dst drive if it doesn't have enough free space to hold a completed plot? 

**System setup:**
 - OS: Ubuntu Server 20.04 LTS
 - Method of archiving: None. Section commented out in config file.

**Config**
<details> <summary>full configuration</summary>

```yaml
# paste your complete configuration file contents here.
```

</details>

**Additional context & screenshots**

**Comment by SebastianMetzger** [comment]
I currently use plotman without archive function, but mounted couple of drives on my plotting machine as dest folders. 

Would love to have this functionality as well. Currently it does depriotizize drives that are full, but it will still start new plots for it occactionally.

**Comment by danielyankowski** [comment]
Similar problem here. As you can see I have free space on both dst drives, however Plotman distributes the plots unevenly, really prioritizing drive which has less free space.
![image](https://user-images.githubusercontent.com/10847257/120479501-4daf6c00-c3ae-11eb-9517-27cf4ac863d6.png)

**Comment by altendky** [comment]
dst is meant as a buffer.  Archive is meant to distribute plots to their final resting place.  Presently, it is annoying to setup archiving for local drives since you have to use rsyncd regardless.  There's a fix for that but we need a bit more testing and documentation work.  It will be in the next release.

> why would it continue writing to a dst drive if it doesn't have enough free space to hold a completed plot?

Because dst is a buffer.  It is meant to be continuously cleared by archiving, or your own alternative to archiving.  As such, the free space available when a plot starts is expected to have no relevance to the amount of free space when the plot ends hours later.

**Comment by SebastianMetzger** [comment]
@altendky This sounds good, would be exactally what I need 😎 Keep it up! 🚀

**Comment by jayhohoho2019** [comment]
> dst is meant as a buffer. Archive is meant to distribute plots to their final resting place. Presently, it is annoying to setup archiving for local drives since you have to use rsyncd regardless. There's a fix for that but we need a bit more testing and documentation work. It will be in the next release.
> 
> > why would it continue writing to a dst drive if it doesn't have enough free space to hold a completed plot?
> 
> Because dst is a buffer. It is meant to be continuously cleared by archiving, or your own alternative to archiving. As such, the free space available when a plot starts is expected to have no relevance to the amount of free space when the plot ends hours later.

This makes sense, but chia plots create already has a buffer which is the temp drive.  If plotman adds another layer that is fine too, but then it allows disabling archiving, in which case the dst drives should become the final destination.  Imo the code should handle this.    If archive mode is disabled or a flag is set, make the dst drives archive drives.

**Comment by altendky** [comment]
'tmp' isn't 'a buffer for completed plots' provided by the chia plotting process...  it's a working directory for temporary files.  And no, I'm not going to make it so you can use archiving by disabling archiving and not configuring it.  At least not right now...  Rather, I've spent a bunch of time making archiving both easier to use for local drives and more flexible for 'power users'.

Yes, there are lots of reasons that people want to avoid archiving.  Lots of valid reasons.  Also lots of confusion.  If you want files distributed amongst multiple drives to fill them then you want archiving.  That's it.  It is the code that has the logic you want.  You can wish we called it `dst` or that it didn't require rsyncd for local drives or whatever...  but it has the 'distribute plots among drives until they are full' feature that everyone is asking for.

Anything we pass to the chia plotting process must be decided many hours in advance.  This is not a great way to operate in general.  Rather, just wait until that process is done, check where the result should go, put it there.  This is already implemented.  It has been made much easier to use (PR needs merged and released).  There are plans to make it even more powerful and flexible.  I do not plan to make all those improvements in a much less flexible and complicated way by having to tell the chia plotting process what to do hours ahead of time.

Anyways, all the discussions on this seem to be about the terminology which seems the least relevant of all.  If there is some functionality needed then let's discuss it.  Such as 'distributing plots among drives to fill them all' (archiving) or 'having an efficient local buffer that is used only when needed because archiving to a remote location is having trouble' and 'multiple archival targets' (both 'planned'/imagined future archiving features).

I have updated [the wiki page](https://github.com/ericaltendorf/plotman/wiki/Archiving) recently to attempt to convey the intended use of archiving.  You can also follow the link from there to the gist to see the updated page for the new archiving configuration.

`dst` isn't a great name for those disks from a plotman perspective.  It would be great if we could move past that terminology and look at the functionality instead.

**Comment by dantodd** [comment]
My system uses a jbod directly attached to the plotter and having some intelligent management of plot distribution based on drive space would be REALLY helpful.

**Comment by jayhohoho2019** [comment]
This is exactly what I'm trying to convey also.  In my setup the plotman
"archive drives" are local to the plotters using jbods, so this
functionality of filling them up until full is needed on local drives, in
which case I'd think it'd make sense to skip the plotman buffer "dst
drives？“

**Comment by altendky** [comment]
@dantodd what do you think archiving is?  Hint, it is exactly that.

@jayhohoho2019 sure.  You were always able to specify dst to be the same as tmp when you had one tmp drive.  This is of course not sufficiently flexible so someone made it more so and now you can have that functionality with multiple tmp drives.  (on development)

If you don't want buffer drives don't have buffer drives.  I don't have buffer drives...  Archiving distributes plots to fill drives.  I use it for both local and remote drives.  I have done this for a long time.  Most of us want this but for various reasons many people refuse to use the feature that does what they want.  Yes, it has been a hassle to setup for local drives what with it pointlessly using rsyncd...  that is why I spent a bunch of time fixing that and making it easy (but also being more customizable because lots of people want that too).  Please stop prescribing what the implementation should be when I have already implemented the functionality you want.  It is present on development.  Entirely comment out the dst configuration if you do not want dedicated buffer drives.  If you want plotman to distribute your plots to fill a group of local drives, use the new local rsync archiving target...

Archiving is _not_ about the drives being remote.  Yes, the wiki said it was and I have corrected that.  My apologies for the confusion there.  Archiving is about filling all the drives even as new ones are added while plots are in progress.  That is what everyone wants.  Please use archiving or explain the functional problem with it.  "it is overly complicated to setup for local drives" was a fair complaint (still is in terms of released code).  I have acknowledged that for a long time and we have worked a lot on it.  I'm sorry it took so long to get done.  There are various reasons and things I could have done differently to get it done sooner.  So it goes...  It is now usable on the `development` branch and hopefully gets released soon.

**Comment by jayhohoho2019** [comment]
Thanks for the clarification. This helps. Just wanted to double check on a
few things:
1.  Skipping dst drives for local archive drives.  Is this supported in the
current release? So just use tmp drive as dst, and set up archive?
2. When will the new release with local archive support (not using rsyncd)
coming out?

Thank you.

**Comment by altendky** [comment]
1. If you have one tmp drive, you can specify that same drive as dst in the v0.3.1 release.  If you have multiple tmp drives you need to use the `development` branch at the moment.  With that, or the next release, you would entirely comment out the dst section of the config to have it use tmp (or tmp2, if specified) instead.
2. Release maybe in the next days or a week?  My hope is sooner than later, but we'll see.  I don't know of any big work to be done, just settling and hopefully getting some feedback from people testing `development`.

**Comment by jayhohoho2019** [comment]
Awesome.  Could we get a notice here when it's released?  Can't wait to try
it.

**Comment by jayhohoho2019** [comment]
Btw, this might not be the best place to discuss archiving, but is it
supported to have multiple plotters all archive (over rsyncd）to the same
host computer that has multiple JBODs daisy chained to it?

**Comment by altendky** [comment]
'multiple JBODs' isn't relevant as each drive is just a drive.  Get it mounted to a directory inside of the configured directory and it should (eventually) get filled.  On the multiple plotters side, that's what the `index:` value is for.  Give each plotter an index counting from zero and they will generally plot to different drives to avoid IO contention.  Pretty simplistic, but generally useful.

And sure, help generally belongs in GitHub discussions or in #plotman on the chia keybase.  `:]`

**Comment by jayhohoho2019** [comment]
Thanks.  One more followup question, in this scenario the host computer
with multiple JBODs attached to it is a plotter too.  So it will just get
its own index, but do archiving over local drives (which in the new release
would not use rsyncd)?

**Comment by altendky** [comment]
Yup.  Lately I have been running two plotters, one as a dedicated plotter with remote/rsyncd and the other as plotter with local rsync.  One with an index of 0 and the other with an index of 1.

**Comment by azereki** [comment]
> Yup. Lately I have been running two plotters, one as a dedicated plotter with remote/rsyncd and the other as plotter with local rsync. One with an index of 0 and the other with an index of 1.

I have a similar setup, except that I am plotting on two machines and filling local dst drives, with one farming/harvesting all the plot drives over mounted network shortcuts. 

I couldn't figure out if it was user error or software error that was causing me to encounter the same issue as OP. I didn't understand why or how I was supposed to use archiving just from initially reading the wiki alone. I recently updated to v0.4.1, read the new config file comments and found this thread, which helped clarify things a lot. Going to update my setup accordingly, thank you!

**Comment by jayhohoho2019** [comment]
> Yup. Lately I have been running two plotters, one as a dedicated plotter with remote/rsyncd and the other as plotter with local rsync. One with an index of 0 and the other with an index of 1.

I'm using v0.4.1's archive.  Local only for now.  Works very well.  Thanks. I'm wondering if a plotter could do local rsync and remote rsyncd at the same time, each with its own site_root.

**Comment by altendky** [comment]
We do not presently support multiple archival targets from one plotman instance, no.  Fill one, switch to the other.  But yes, that idea has been floating around in my head, just hasn't gotten any sort of priority.

**Comment by jayhohoho2019** [comment]
I'm setting up rsync on v0.4.1.  Two questions:
1. What is site under env?  Your sample entry is "site: sites"  What does that mean?
2. Where would index be added?  Under env: ? index:n where n is an integer?

**Comment by altendky** [comment]
1. The rsyncd module name.
2. `archiving:` `index:`
3. `archiving:` at the top level is the new one.  If you want to control the rsync command line options there is `env:` `options:`.  Here are the defaults. 
 https://github.com/ericaltendorf/plotman/blob/6de45518b211951b45b26b6e63d25b401d82f862/src/plotman/resources/target_definitions.yaml#L34

* Yes, I need to take another pass through the documentation to fix it.
* Yes, the names could afford to be a bit different.
* Yes, I need to create a proper and complete and maintainable (generated) schema (documentation) for the configuration file.

Plenty of work left to do.

**Comment by jayhohoho2019** [comment]
Thanks.  I got it to work.  Two plotters rsync to a third host running rsyncd, which runs local_rsync as well.  Each with a different index, and they do write to different drives. Default options for rsync except bwlimit=200000.  I'm wondering if you have any recommendations on tuning rsync parameters.  I've noticed that my drives inside a 5 bay drive enclosure (on USB) share a bandwidth of around 250MB/s, and the local_rsync, when running, always gets about 150MB of it, leaving around 100MB for the two remote rsync clients to share.  When local_rsync is not rsyncing, and the other two are, the other two get the full 250MB or so between them.

**Comment by altendky** [comment]
We don't have any means by which to dynamically change the bandwidth limit.  Depending what you are limiting for, perhaps figuring out ionice for rsyncd would be a good option.  I haven't dug into it yet.

**Comment by jayhohoho2019** [comment]
If I update the rsync options in config.yaml, stop plotman archive and restart it, does plotman check whether an rsync is still running from the previous run (same target type, local or rsyncd)?

**Comment by altendky** [comment]
It shouldn't find a local if using remote, or vice versa, but otherwise yes.  The awareness of rsync processes is only by way of looking at the process list, not remembering what has been launched.

**Comment by hajes** [comment]
I second that.

Yesterday, one destination drive run out of the free space. Plotman happily plots to full destination drive again despite there is 5 more drives with enough free space ;-)

What is point of checking free disk space if Plotman still use drive for plotting?

**Comment by jayhohoho2019** [comment]
Closing this as a bug.  Please read the comments about using archive mode.

**Comment by altendky** [comment]
> I second that.
> 
> Yesterday, one destination drive run out of the free space. Plotman happily plots to full destination drive again despite there is 5 more drives with enough free space ;-)
> 
> What is point of checking free disk space if Plotman still use drive for plotting?

Available space is being checked for archiving disks not dst.  See an explanation of archiving, including why, in [the archiving wiki page](https://github.com/ericaltendorf/plotman/wiki/Archiving).
