### ISSUE TITLE
Check in a current and canonicalized config.yaml

### ISSUE THREAD

**Issue by ericaltendorf** [ericaltendorf/plotman#7]
need to do a fork of my local config.yaml so i can maintain both my own version for use and a canonical default for the github repository.

see: https://gist.github.com/eFishCent/dcce711d6babb123d8ab8d0ba3dc0532

**Comment by altendky** [comment]
Is this done since the merge happened?  Or is there more to do.

**Comment by ericaltendorf** [comment]
The config checked in is now a good template.  We should still make a better way for people to customize their own config without editing the source code tree, but maybe that is done now too?

**Comment by altendky** [comment]
https://github.com/ericaltendorf/plotman/issues/84 is what has come of the related discussions.  As installation is recommended now on `development` you do not clone the source (pip does, but you don't).  @jkbecker has been talking about options for having plotman grow a command to write out a config file to it's 'preferred' location rather than making users go to GitHub to get a copy to start from.

It sounds like this issue is done.  It sounds like maybe another ticket should be created for the create-a-config-for-the-user feature?

**Comment by ericaltendorf** [comment]
That makes sense to me.
